- hosts: win
  gather_facts: no
  tasks:
    - name: Test PowerShell
      win_shell: |
        Get-Host
      register: result_get_host

    - name: Display result of Get-Host
      debug:
        var: result_get_host.stdout